### ISSUE TITLE
USER STORY 2: Submit a poll response

### ISSUE THREAD

**Issue by gozygreg** [gozygreg/My-first-agile-project#4]
In order to have the option to provide anonymous feedback as a user, I can decide to hide or show my identity in the poll response 
 
# Acceptance Criteria:
- The option should be provided as a checkbox
- The checkbox should be "checked" by default
-  The option should appear next to the submit button
-  After submitting the default submission confirmation should be adjusted to include the user name.

# Tasks
- [ ] Update the view: the poll design (HTML and CSS) to include the checkbox and to show the name of the submitter
- [ ] Create a new field in the model to track the username
- [ ] update the controller function
- [ ] Test the functionality
