### ISSUE TITLE
USER STORY 5: Manage a Poll

### ISSUE THREAD

**Issue by gozygreg** [gozygreg/My-first-agile-project#7]
In order to automatically hide the poll as an administrator, I can pick the expiry date while publishing the poll

## Acceptance Criteria:
-  The poll should disappear at 11:59 PM on the target date
- The real estate of the "poll" should be reserved on the home page. A message that says "Stay tuned, a new poll is coming soon" should appear if no other Poll is active
- The administrator expiry date should be at least 3 days after the current date.

## Task
- [ ] Update the admin module view: the poll design (HTML and CSS) to include date picker
- [ ] Update the website view: show "Stay Tuned, a new Poll is coming soon"
- [ ] Create a JavaScript function to validate the expiry date is at least after 3 days.
- [ ] Create job to check the expiry Polls everyday at 11:59 pm and Hide them
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality
